name: Smoke Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Golang
      run: brew install golang

    - name: Build Rails Init
      run: go build

    - name: Run rails-init
      run: ./rails-init


    # - name: Install rails-init
    #   run: |
    #     brew tap radar/rails-init git@github.com:radar/rails-init-homebrew-tap
    #     brew install rails-init

    # - name: Run rails-init
    #   run: |
    #     rails-init
