name: Ruby

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: GitHub Action for Homebrew
      run: |
        which brew
