name: Smoke Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: run
      uses: cedrickring/golang-action@1.4.1

    - name: Run rails-init
      run: ./rails-init
