name: Smoke Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Homebrew package dependency
    - name: Install asdf
      run: brew install asdf

    - name: Install Golang
      run: brew install golang

    - name: Build Rails Init
      run: go build

    # - name: Run rails-init
    #   run: ./rails-init

    - name: Check Node version
      run: |
        node -v
        which node
        . /usr/local/opt/asdf/asdf.sh
        bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
        asdf install nodejs 13.6.0
        asdf list nodejs
        asdf global nodejs 13.6.0
        node -v
        which node


    # - name: Install rails-init
    #   run: |
    #     brew tap radar/rails-init git@github.com:radar/rails-init-homebrew-tap
    #     brew install rails-init

    # - name: Run rails-init
    #   run: |
    #     rails-init
