name: Smoke Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Curl ryanbigg.com
      run: curl https://ryanbigg.com

    # Homebrew package dependency
    - name: Install asdf + gpg
      run: brew install asdf gpg

    - name: Install Golang
      run: brew install golang

    - name: Build Rails Init
      run: go build

    - name: Run rails-init
      run: |
        . /usr/local/opt/asdf/asdf.sh
        ./rails-init

    - name: Check asdf list & current
      run: |
        asdf list
        asdf current


    - name: Check Node & yarn versions
      run: |
        . /usr/local/opt/asdf/asdf.sh
        which node
        node -v
        which yarn
        yarn -v

    - name: Check Ruby version
      run: |
        . /usr/local/opt/asdf/asdf.sh
        which ruby
        ruby -v

    - name: Check Rails version
      run: |
        . /usr/local/opt/asdf/asdf.sh
        which rails
        rails -v
