name: Smoke Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Homebrew package dependency
    - name: Install asdf, coreutils, gpg
      run: brew install asdf coreutils gpg

    - name: Install Golang
      run: brew install golang

    - name: Build Rails Init
      run: go build

    - name: Run rails-init
      run: |
        . /usr/local/opt/asdf/asdf.sh
        ./rails-init

    - name: Check Node version
      run: |
        . /usr/local/opt/asdf/asdf.sh
        node -v
        which node
        asdf plugin-add nodejs
        asdf plugin list
        bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
        asdf install nodejs 13.6.0
        asdf list nodejs
        asdf global nodejs 13.6.0
        node -v
    #     which node


    # - name: Install rails-init
    #   run: |
    #     brew tap radar/rails-init git@github.com:radar/rails-init-homebrew-tap
    #     brew install rails-init

    # - name: Run rails-init
    #   run: |
    #     rails-init
